version: '3.3'
services:

  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:latest
    environment:
     - POST_SERVICE_HOST=post
     - POST_SERVICE_PORT=5000
     - COMMENT_SERVICE_HOST=comment
     - COMMENT_SERVICE_PORT=9292
    ports:
      - 9292:9292/tcp
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:latest
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - back_net
      - front_net
volumes:
  prometheus_data:
  post_db:

networks:
  front_net:
  back_net:
