version: '3.3'
services:
  post_db:
    env_file:
      - reddit.env
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file:
      - reddit.env
    image: ${USERNAME}/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    env_file:
      - reddit.env
    image: ${USERNAME}/post:latest
    networks:
      - front_net
      - back_net
  comment:
    env_file:
      - reddit.env
    image: ${USERNAME}/comment:latest
    networks:
      - back_net
      - front_net
      
volumes:
  post_db:

networks:
  front_net:
  back_net:
